// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CapitalizeController from "./capitalize_controller"
application.register("capitalize", CapitalizeController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
