development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://default:wFob4MQ1gr4ntgZMzHx4eThGaEjsyBk4@redis-17689.c270.us-east-1-3.ec2.cloud.redislabs.com:17689" } %>
  channel_prefix: follow_horse2_production
